<?php
                                        	


  $ConstantsArray = array('dbServerUrl' => '/Applications/MAMP/htdocs/elive/app/',

  'applicationURL'=>'http://localhost/elive/app/',
  'rootURL'=>'http://localhost/elive/',
  'logger' => 'myDBLogger'
  );

  $PERMISSION_MANAGER = "Manager";

  $PERMISSION_USER = "User";

  

  $Log4PHP_MyDBLogger = "myDBLogger";

  $Log4PHP_MyMailerLogger = "myMailerLogger";

  $Log4PHP_MyFileLogger = "myFileLogger";



?>